export const homeObjOne = {
  id: "about",
  lightBg: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "Who We Are",
  headLine: "K & R Events",
  description: "All your Wedding Needs",
  imgStart: false,
  img: require("../images/Headshot.jpg"),
  alt: "portrait",
  dark: false,
  primary: true,
  darkText: true,
};

export const homeObjTwo = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Who We Are",
  headLine: "K & R Events",
  description: "All your Wedding Needs",
  imgStart: true,
  img: require("../images/Flowers.jpg"),
  alt: "portrait",
  dark: false,
  primary: true,
  darkText: true,
};

export const homeObjThree = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Who We Are",
  headLine: "K & R Events",
  description: "All your Wedding Needs",
  imgStart: false,
  img: require("../images/Gradimages.jpg"),
  alt: "portrait",
  dark: false,
  primary: true,
  darkText: true,
};
